---
- name: disable Virtual servers
  hosts: localhost
  connections: local
  gather_facts: false
  var_files:
    "group_vars/datacenter/lb.yaml"


  tasks:
  - name: Disable Single Virtual Server in Datacenter
    include_role:
      name: singlenode
